v6:
  - base-branch: ['v6']

documentation:
  - head-branch: ['^doc']
  - changed-files:
      - any-glob-to-any-file: ['documents/**/*.md', 'README.md']

dependencies:
  - head-branch: ['^dependencies', '^deps']
  - changed-files:
      - any-glob-to-any-file: ['**/*/package.json']

ci:
  - head-branch: ['^ci']
  - changed-files:
      - any-glob-to-any-file: ['.github/**/*.yml']

unit-testing:
  - head-branch: ['^test']
  - changed-files:
      - any-glob-to-any-file: ['__test__/**/*', '__snapshots__/**/*.md']

accessibility:
  - head-branch: ['^accessibility', '^a11y']

bug:
  - head-branch: ['^fix', '^bug']

enhancement:
  - head-branch: ['^feat']

performance:
  - head-branch: ['^perf']

refactor:
  - head-branch: ['^refactor']
