v6:
  - base-branch: ['v6']

v7:
  - base-branch: ['v7']

accessibility:
  - base-branch: ['^accessibility', '^a11y']

bug:
  - head-branch: ['^fix', '^bug']

enhancement:
  - head-branch: ['^feat']

documentation:
  - changed-files: '**/*.md'

ci:
  - changed-files: '**/*.yml'

performance:
  - head-branch: ['^perf']
