name: 'Setup Environment and Resources'
description: 'Setup node.js and caching scoped within a workflow'

runs:
  using: 'composite'
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 18.x
        cache: 'npm'

    - name: Setup caching dependencies
      uses: actions/cache@v3
      id: cache-node_modules
      with:
        path: |
          node_modules
          */node_modules
          */*/node_modules
        key: node_modules-${{ github.run_id }}

    - name: Setup caching build
      uses: actions/cache@v3
      id: cache-build
      with:
        path: |
          packages/*/lib
          packages/*-theme/**/*.js
          packages/*-theme/**/*.css
        key: build-${{ github.run_id }}

    - name: Setup caching test result
      uses: actions/cache@v3
      id: cache-test-result
      with:
        path: packages/*/coverage
        key: test-result-${{ github.run_id }}
