name: 'Setup Environment and Resources'
description: 'Setup environment, resources and caching'

outputs:
  cache-dependencies-hit:
    description: "Use dependencies cache"
    value: ${{ steps.cache-npm.outputs.cache-hit }}
  cache-build-hit:
    description: "Use build output scripts cache"
    value: ${{ steps.cache-build.outputs.cache-hit }}

runs:
  using: "composite"
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16.x

    - name: Setup caching dependencies
      uses: actions/cache@v2
      id: cache-npm
      with:
        path: |
          node_modules
          */node_modules
          */*/node_modules
        key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
        restore-keys: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}

    - name: Setup caching build
      uses: actions/cache@v2
      id: cache-build
      with:
        path: |
          packages/*/lib
          packages/*-theme/**/*.js
          packages/*-theme/**/*.css
        key: ${{ runner.os }}-build-2d0dcc19567f26528fdf58aff20d9fc617400408
        restore-keys: ${{ runner.os }}-build-2d0dcc19567f26528fdf58aff20d9fc617400408
