name: 'Setup Environment and Resources'
description: 'Setup environment, resources and caching'

outputs:
  cache-dependencies-hit:
    description: "Use dependencies cache"
    value: ${{ steps.cache-npm.outputs.cache-hit }}
  cache-build-hit:
    description: "Use build output scripts cache"
    value: ${{ steps.cache-build.outputs.cache-hit }}
  cache-test-result-hit:
    description: "Use test result output cache"
    value: ${{ steps.cache-test-result.outputs.cache-hit }}

runs:
  using: "composite"
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18.14.0

    - name: Setup caching dependencies
      uses: actions/cache@v3
      id: cache-npm
      with:
        path: |
          node_modules
          */node_modules
          */*/node_modules
        key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}

    - name: Setup caching build
      uses: actions/cache@v3
      id: cache-build
      with:
        path: |
          packages/*/lib
          packages/*-theme/**/*.js
          packages/*-theme/**/*.css
        key: ${{ runner.os }}-build-${{ github.sha }}

    - name: Setup caching test result
      uses: actions/cache@v3
      id: cache-test-result
      with:
        path: packages/*/coverage
        key: ${{ runner.os }}-test-result-${{ github.sha }}
