name: 'Setup environment and resources with build'
description: 'Setup node.js, install dependencies and build.
  Dependencies and build results are cached scoped within a workflow so they would run once.'
inputs:
  build-script:
    description: build script for be run
    required: false
    default: npm run build

  pre-build-script:
    description: script to be run before build-script
    required: false
    default: ''

runs:
  using: "composite"
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18.x
        cache: 'npm'

    - name: Setup caching dependencies
      uses: actions/cache@v3
      id: cache-node_modules
      with:
        path: |
          node_modules
          */node_modules
          */*/node_modules
        key: node_modules-${{ github.run_id }}-${{ github.run_attempt }}

    - name: Install dependencies
      shell: bash
      if: steps.cache-node_modules.outputs.cache-hit != 'true'
      run: npm ci --ignore-scripts --audit=false --fund=false

    - name: Setup caching build
      uses: actions/cache@v3
      id: cache-build
      with:
        path: |
          packages/*/lib
          packages/*-theme/**/*.js
          packages/*-theme/**/*.css
        key: build-${{ github.run_id }}-${{ github.run_attempt }}

    - name: Pre-build
      shell: bash
      if: steps.cache-build.outputs.cache-hit != 'true' && inputs.pre-build-script != ''
      run: ${{ inputs.pre-build-script }}

    - name: Build
      shell: bash
      if: steps.cache-build.outputs.cache-hit != 'true'
      run: ${{ inputs.build-script }}
