/* @web/test-runner snapshot v1 */
export const snapshots = {};

snapshots["combo-box/Value Selection by Value Attribute Data Selected: Afghanistan"] = 
`<div part="input-wrapper">
  <input
    aria-activedescendant="AF"
    aria-autocomplete="list"
    aria-expanded="true"
    aria-haspopup="listbox"
    aria-owns="internal-list"
    autocomplete="off"
    part="input"
    role="combobox"
    type="text"
  >
  <div
    id="toggle-button"
    part="button button-toggle"
  >
    <ef-icon
      icon="down"
      part="icon icon-toggle"
    >
    </ef-icon>
  </div>
</div>
<ef-overlay-viewport>
</ef-overlay-viewport>
<ef-overlay
  no-autofocus=""
  no-focus-management=""
  no-overlap=""
  opened=""
  part="list"
  tabindex="-1"
  with-shadow=""
>
  <ef-list
    aria-multiselectable="false"
    id="internal-list"
    role="listbox"
    tabindex=""
  >
    <ef-list-item
      aria-selected="false"
      role="presentation"
      type="header"
    >
    </ef-list-item>
    <ef-list-item
      aria-selected="true"
      highlighted=""
      id="AF"
      role="option"
      selected=""
    >
    </ef-list-item>
    <ef-list-item
      aria-selected="false"
      id="AX"
      role="option"
    >
    </ef-list-item>
    <ef-list-item
      aria-selected="false"
      id="AL"
      role="option"
    >
    </ef-list-item>
  </ef-list>
</ef-overlay>
`;
/* end snapshot combo-box/Value Selection by Value Attribute Data Selected: Afghanistan */

snapshots["combo-box/Value Selection by Value Attribute Value attribute is selected"] = 
`<div part="input-wrapper">
  <input
    aria-activedescendant="AF"
    aria-autocomplete="list"
    aria-expanded="true"
    aria-haspopup="listbox"
    aria-owns="internal-list"
    autocomplete="off"
    part="input"
    role="combobox"
    type="text"
  >
  <div
    id="toggle-button"
    part="button button-toggle"
  >
    <ef-icon
      icon="down"
      part="icon icon-toggle"
    >
    </ef-icon>
  </div>
</div>
<ef-overlay-viewport>
</ef-overlay-viewport>
<ef-overlay
  no-autofocus=""
  no-focus-management=""
  no-overlap=""
  opened=""
  part="list"
  tabindex="-1"
  with-shadow=""
>
  <ef-list
    aria-multiselectable="false"
    id="internal-list"
    role="listbox"
    tabindex=""
  >
    <ef-list-item
      aria-selected="false"
      role="presentation"
      type="header"
    >
    </ef-list-item>
    <ef-list-item
      aria-selected="true"
      highlighted=""
      id="AF"
      role="option"
      selected=""
    >
    </ef-list-item>
    <ef-list-item
      aria-selected="false"
      id="AX"
      role="option"
    >
    </ef-list-item>
    <ef-list-item
      aria-selected="false"
      id="AL"
      role="option"
    >
    </ef-list-item>
  </ef-list>
</ef-overlay>
`;
/* end snapshot combo-box/Value Selection by Value Attribute Value attribute is selected */

snapshots["combo-box/Value Selection by Value Attribute Multiple. Data Selected: Afghanistan, Albania"] = 
`<div part="input-wrapper">
  <input
    aria-activedescendant="AF"
    aria-autocomplete="list"
    aria-expanded="true"
    aria-haspopup="listbox"
    aria-owns="internal-list"
    autocomplete="off"
    part="input"
    role="combobox"
    type="text"
  >
  <ef-counter
    max="999"
    part="selection-badge"
    tabindex="-1"
  >
  </ef-counter>
  <div
    id="toggle-button"
    part="button button-toggle"
  >
    <ef-icon
      icon="down"
      part="icon icon-toggle"
    >
    </ef-icon>
  </div>
</div>
<ef-overlay-viewport>
</ef-overlay-viewport>
<ef-overlay
  no-autofocus=""
  no-focus-management=""
  no-overlap=""
  opened=""
  part="list"
  tabindex="-1"
  with-shadow=""
>
  <ef-list
    aria-multiselectable="true"
    id="internal-list"
    role="listbox"
    tabindex=""
  >
    <ef-list-item
      aria-checked="false"
      multiple=""
      role="presentation"
      type="header"
    >
    </ef-list-item>
    <ef-list-item
      aria-checked="true"
      highlighted=""
      id="AF"
      multiple=""
      role="option"
      selected=""
    >
    </ef-list-item>
    <ef-list-item
      aria-checked="false"
      id="AX"
      multiple=""
      role="option"
    >
    </ef-list-item>
    <ef-list-item
      aria-checked="true"
      id="AL"
      multiple=""
      role="option"
      selected=""
    >
    </ef-list-item>
  </ef-list>
</ef-overlay>
`;
/* end snapshot combo-box/Value Selection by Value Attribute Multiple. Data Selected: Afghanistan, Albania */

