name: 'Cache NPM and Build'
description: 'Cache NPM dependencies and and build output scripts'
runs:
  using: "composite"
  steps:
    - name: Setup caching dependencies
        uses: actions/cache@v2
        id: cache-npm
        with:
          path: |
            node_modules
            */*/node_modules
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}

      - name: Install Dependencies
        if: steps.cache-npm.outputs.cache-hit != 'true'
        run: |
          npm ci --ignore-scripts --audit=false --fund=false

      - name: Setup caching build
        uses: actions/cache@v2
        id: cache-build
        with:
          path: |
            packages/*/lib
            packages/*-theme/**/*.js
            packages/*-theme/**/*.css
          key: ${{ runner.os }}-build-${{ github.sha }}
          restore-keys: ${{ runner.os }}-build-${{ github.sha }}

      - name: Build changed packages
        if: steps.cache-build.outputs.cache-hit != 'true'
        run: |
          lerna run build --include-dependencies --since origin/develop...HEAD
