name: 'Run Test'
description: 'Setup Browser and Run Test'

inputs:
  # Support one browser per action for now, because some packages has build script before test
  # which nx cannot send params to karma test after build
  browsers:
    description: 'Target browser(s)'
    required: false
    default: 'default'
  mode:
    description: 'Run test in all packages or only affected packages'
    required: false
    default: 'affected' # affected|all
  target:
    description: 'Run test on the package/element'
    required: false
    default: ''
  coverage:
    description: 'Include test coverage'
    required: false
    default: 'true'
  parallel:
    description: 'Number of test to run concurrently'
    required: false
    default: 1
  https:
    description: 'Enable HTTPS on the test server'
    required: false
    default: 'true'

runs:
  using: "composite"
  steps:
    - name: Setup resources and environment
      uses: ./.github/actions/setup

    - name: Install Playwright Browsers
      shell: bash
      run: |
        npx playwright install --with-deps
        npx playwright --version

    - name: Test
      if: ${{ inputs.target == '' || inputs.target == 'all' }}
      shell: bash
      # Prevent NX caching for mode `all` because it must run all testing, even though the code has not changed.
      run: |
        [[ "${{ inputs.mode }}" == "all" ]] && export NX_SKIP_NX_CACHE=true && unset NX_BASE
        npm run test:${{ inputs.mode }} -- --browserstack ${{ inputs.browsers }} --includeCoverage=${{ inputs.coverage }} --output=minimal --parallel=${{ inputs.parallel }}
      env:
        TEST_HTTPS: ${{ inputs.https }}

    - name: Test Package or Element
      if: ${{ inputs.target != '' && inputs.target != 'all' }}
      shell: bash
      run: |
        npm run test ${{ inputs.target }} -- --browserstack ${{ inputs.browsers }} --includeCoverage=${{ inputs.coverage }}
      env:
        TEST_HTTPS: ${{ inputs.https }}
