name: 'Run Test'
description: 'Setup Browser and Run Test'
inputs:
  # Support one browser per action for now, because some packages has build script before test
  # which nx cannot send params to karma test after build
  browsers:
    description: 'Target browser(s)'
    required: false
    default: 'default'
  mode:
    description: 'Run test in all packages or only affected packages'
    required: false
    default: 'affected' # affected|all
  target:
    description: 'Run test on the package/element'
    required: false
    default: ''
  coverage:
    description: 'Include test coverage'
    required: false
    default: 'true'
  parallel:
    description: 'Number of test to run concurrently'
    required: false
    # Default value 3 is OK for every browsers except Safari need to be one to make it stable
    default: 1
  base:
    description: 'Base SHA for test affected mode'
    required: false
  browserstack:
    description: 'Run test on BrowserStack'
    required: false
    default: 'false'
  username:
    description: 'BrowserStack username'
    required: false
  access-key:
    description: 'BrowserStack access key'
    required: false
runs:
  using: "composite"
  steps:
    - name: 'BrowserStack Environment Setup' # Invokes the setup-env action
      if: ${{ inputs.browserstack == 'true' }}
      uses: browserstack/github-actions/setup-env@master
      with:
        username: ${{ inputs.username }}
        access-key: ${{ inputs.access-key }}

    - name: 'BrowserStack Local Tunnel Setup' # Invokes the setup-local action
      if: ${{ inputs.browserstack == 'true' }}
      uses: browserstack/github-actions/setup-local@master
      with:
        local-testing: start
        local-identifier: random

    - name: Setup resources and environment
      uses: ./.github/actions/setup
      id: setup

    - name: Setup browsers or browserstack command line option
      shell:
      run: |
        [[ "${{ inputs.browserstack }}" == "true" ]] && export BROWSER=browserstack || export BROWSER=browsers
        echo "BROWSERS_OPTION=--$BROWSER='${{ inputs.browsers }}'" >> $GITHUB_ENV

    # Workaround fix NX cannot send param to Karma CLI in some packages
    - name: Update browsers option
      shell:
      run: |
        [[ "${{ inputs.browserstack }}" == "false" && "${{ inputs.browsers }}" == "default" ]] && echo "BROWSERS_OPTION=" >> $GITHUB_ENV
        echo "Updated"

    - name: Test
      if: ${{ inputs.target == '' || inputs.target == 'all' }}
      shell: bash
      # Prevent NX caching for mode `all` because it must run all testing, even though the code has not changed.
      run: |
        [[ "${{ inputs.mode }}" == "affected" ]] && export OPTIONS="--base=${{ inputs.base }}"
        [[ "${{ inputs.mode }}" == "all" ]] && export OPTIONS="--skip-nx-cache"
        npm run test:${{ inputs.mode }} -- $OPTIONS --parallel=${{ inputs.parallel }} ${{ env.BROWSERS_OPTION }} --includeCoverage ${{ inputs.coverage }} --output minimal

    - name: Test Package or Element
      if: ${{ inputs.target != '' }}
      shell: bash
      run: |
        npm run test ${{ inputs.target }} -- ${{ env.BROWSERS_OPTION }} --includeCoverage ${{ inputs.coverage }}

    - name: BrowserStackLocal Stop  # Terminating the BrowserStackLocal tunnel connection
      if: ${{ inputs.browserstack == 'true' }}
      uses: browserstack/github-actions/setup-local@master
      with:
        local-testing: stop
