name: 'Run Test On Browser'
description: 'Setup Browser and Run Test'
inputs:
  browsers:
    description: 'List of browser name'
    required: true
  mode:
    description: 'Test mode'
    required: false
    default: 'affected' # affected|all
  coverage:
    description: 'Include test covertage'
    required: false
    default: 'true'
  parallel:
    description: 'Run parallel testing limit'
    required: false
    # Default value 3 is OK for every browsers except Safari need to be one to make it stable
    default: 1
  base:
    description: 'Base sha for test affected mode'
    required: false
  browserstack:
    description: 'Run test on BrowserStack'
    required: false
    default: 'false'
  username:
    description: 'BrowserStack username'
    required: false
  access-key:
    description: 'BrowserStack access key'
    required: false
runs:
  using: "composite"
  steps:
    # - name: 'BrowserStack Env Setup' # Invokes the setup-env action
    #   if: ${{ inputs.browserstack == 'true' }}
    #   uses: browserstack/github-actions/setup-env@master
    #   with:
    #     username: ${{ inputs.username }}
    #     access-key: ${{ inputs.access-key }}

    # - name: 'BrowserStack Local Tunnel Setup' # Invokes the setup-local action
    #   if: ${{ inputs.browserstack == 'true' }}
    #   uses: browserstack/github-actions/setup-local@master
    #   with:
    #     local-testing: start
    #     local-identifier: random

    - name: Setup resources and environment
      uses: ./.github/actions/setup
      id: setup

    - name: Create browsers command line option
      shell:
      # Toggle browsers and browserstack options and save to GitHub environment variable
      run: |
        [[ "${{ inputs.browserstack }}" == "true" ]] && export BROWSER="browserstack" || export BROWSER="browsers"
        echo "BROWSERS_OPTION=\"--$BROWSER='${{ inputs.browsers }}'\"" >> $GITHUB_ENV

    # - name: Test All
    #   if: ${{ inputs.mode == 'all' }}
    #   shell: bash
    #   # Prevent NX caching because it must run all testing, even though the code has not chaged.
    #   run: npm run test:all -- --parallel=${{ inputs.parallel }} --skip-nx-cache ${{ env.BROWSERS_OPTION }} --includeCoverage ${{ inputs.coverage }} --output minimal

    - name: Test
      shell: bash
      run: |
        [[ "${{ inputs.mode }}" == "affected" ]] && export OPTIONS="--base=${{ inputs.base }}"
        [[ "${{ inputs.mode }}" == "all" ]] && export OPTIONS="--skip-nx-cache"
        npm run test:${{ inputs.mode }} -- $OPTIONS --parallel=${{ inputs.parallel }} ${{ env.BROWSERS_OPTION }} --includeCoverage ${{ inputs.coverage }} --output minimal

    # - name: BrowserStackLocal Stop  # Terminating the BrowserStackLocal tunnel connection
    #   if: ${{ inputs.browserstack == 'true' }}
    #   uses: browserstack/github-actions/setup-local@master
    #   with:
    #     local-testing: stop



