/* @web/test-runner snapshot v1 */
export const snapshots = {};

snapshots["select/Selection Selection by Selected Property Options Selected: Afghanistan"] = 
`<div
  aria-controls="menu"
  aria-expanded="true"
  aria-haspopup="listbox"
  aria-invalid="false"
  aria-required="false"
  id="box"
  placeholder="Placeholder"
  role="combobox"
  tabindex="0"
>
  <div id="text">
    <div part="label">
      Afghanistan
    </div>
  </div>
  <ef-icon
    aria-hidden="true"
    icon="down"
    part="icon"
  >
  </ef-icon>
</div>
<div id="trigger">
</div>
<ef-overlay-viewport>
</ef-overlay-viewport>
<ef-overlay
  focused=""
  id="menu"
  lock-position-target=""
  opened=""
  part="list"
  role="listbox"
  tabindex="-1"
  with-shadow=""
>
  <slot>
  </slot>
</ef-overlay>
`;
/* end snapshot select/Selection Selection by Selected Property Options Selected: Afghanistan */

snapshots["select/Selection Selection by Selected Property Data Selected: Afghanistan"] = 
`<div
  aria-controls="menu"
  aria-expanded="true"
  aria-haspopup="listbox"
  aria-invalid="false"
  aria-required="false"
  id="box"
  placeholder="Placeholder"
  role="combobox"
  tabindex="0"
>
  <div id="text">
    <div part="label">
      Afghanistan
    </div>
  </div>
  <ef-icon
    aria-hidden="true"
    icon="down"
    part="icon"
  >
  </ef-icon>
</div>
<div id="trigger">
</div>
<ef-overlay-viewport>
</ef-overlay-viewport>
<ef-overlay
  focused=""
  id="menu"
  lock-position-target=""
  opened=""
  part="list"
  role="listbox"
  tabindex="-1"
  with-shadow=""
>
  <ef-item
    aria-selected="false"
    part="item"
    role="presentation"
    tabindex="-1"
    type="header"
  >
  </ef-item>
  <ef-item
    aria-selected="true"
    highlighted=""
    part="item"
    role="option"
    selected=""
    tabindex="0"
  >
  </ef-item>
  <ef-item
    aria-selected="false"
    part="item"
    role="option"
    tabindex="0"
  >
  </ef-item>
  <ef-item
    aria-selected="false"
    part="item"
    role="presentation"
    tabindex="-1"
    type="divider"
  >
  </ef-item>
  <ef-item
    aria-selected="false"
    part="item"
    role="option"
    tabindex="0"
  >
  </ef-item>
</ef-overlay>
`;
/* end snapshot select/Selection Selection by Selected Property Data Selected: Afghanistan */

snapshots["select/Selection Selection by Selected Property Data Selected change"] = 
`<div
  aria-controls="menu"
  aria-expanded="true"
  aria-haspopup="listbox"
  aria-invalid="false"
  aria-required="false"
  id="box"
  placeholder="Placeholder"
  role="combobox"
  tabindex="0"
>
  <div id="text">
    <div part="label">
      Albania
    </div>
  </div>
  <ef-icon
    aria-hidden="true"
    icon="down"
    part="icon"
  >
  </ef-icon>
</div>
<div id="trigger">
</div>
<ef-overlay-viewport>
</ef-overlay-viewport>
<ef-overlay
  focused=""
  id="menu"
  lock-position-target=""
  opened=""
  part="list"
  role="listbox"
  tabindex="-1"
  with-shadow=""
>
  <ef-item
    aria-selected="false"
    part="item"
    role="presentation"
    tabindex="-1"
    type="header"
  >
  </ef-item>
  <ef-item
    aria-selected="false"
    highlighted=""
    part="item"
    role="option"
    tabindex="0"
  >
  </ef-item>
  <ef-item
    aria-selected="false"
    part="item"
    role="option"
    tabindex="0"
  >
  </ef-item>
  <ef-item
    aria-selected="false"
    part="item"
    role="presentation"
    tabindex="-1"
    type="divider"
  >
  </ef-item>
  <ef-item
    aria-selected="true"
    part="item"
    role="option"
    selected=""
    tabindex="0"
  >
  </ef-item>
</ef-overlay>
`;
/* end snapshot select/Selection Selection by Selected Property Data Selected change */

snapshots["select/Selection Selection by Selected Property Data Unselected"] = 
`<div
  aria-controls="menu"
  aria-expanded="true"
  aria-haspopup="listbox"
  aria-invalid="false"
  aria-required="false"
  id="box"
  placeholder="Placeholder"
  role="combobox"
  tabindex="0"
>
  <div id="text">
    <div part="placeholder">
      Placeholder
    </div>
  </div>
  <ef-icon
    aria-hidden="true"
    icon="down"
    part="icon"
  >
  </ef-icon>
</div>
<div id="trigger">
</div>
<ef-overlay-viewport>
</ef-overlay-viewport>
<ef-overlay
  focused=""
  id="menu"
  lock-position-target=""
  opened=""
  part="list"
  role="listbox"
  tabindex="-1"
  with-shadow=""
>
  <ef-item
    aria-selected="false"
    part="item"
    role="presentation"
    tabindex="-1"
    type="header"
  >
  </ef-item>
  <ef-item
    aria-selected="false"
    highlighted=""
    part="item"
    role="option"
    tabindex="0"
  >
  </ef-item>
  <ef-item
    aria-selected="false"
    part="item"
    role="option"
    tabindex="0"
  >
  </ef-item>
  <ef-item
    aria-selected="false"
    part="item"
    role="presentation"
    tabindex="-1"
    type="divider"
  >
  </ef-item>
  <ef-item
    aria-selected="false"
    part="item"
    role="option"
    tabindex="0"
  >
  </ef-item>
</ef-overlay>
`;
/* end snapshot select/Selection Selection by Selected Property Data Unselected */

