/* @web/test-runner snapshot v1 */
export const snapshots = {};

snapshots["collapse/Collapse Should Have Correct DOM Label and DOM structure is correct with spacing"] = 
`<ef-header
  level="3"
  part="header"
>
  <div
    part="heading"
    role="heading"
  >
    <div
      aria-controls="content"
      aria-expanded="false"
      id="header-toggle"
      part="header-toggle"
      role="button"
      tabindex="0"
    >
    </div>
  </div>
  <ef-icon
    aria-hidden="true"
    icon="right"
    part="toggle"
    slot="left"
  >
  </ef-icon>
  <slot
    name="header-left"
    slot="left"
  >
  </slot>
  <slot
    name="header-right"
    slot="right"
  >
  </slot>
</ef-header>
<div
  aria-labelledby="header-toggle"
  id="content"
  part="content"
  role="region"
>
  <ef-panel
    part="content-data"
    transparent=""
  >
    <slot>
    </slot>
  </ef-panel>
</div>
`;
/* end snapshot collapse/Collapse Should Have Correct DOM Label and DOM structure is correct with spacing */

snapshots["collapse/Collapse Should Have Correct DOM Label and DOM structure is correct with level"] = 
`<ef-header
  level="1"
  part="header"
>
  <div
    part="heading"
    role="heading"
  >
    <div
      aria-controls="content"
      aria-expanded="false"
      id="header-toggle"
      part="header-toggle"
      role="button"
      tabindex="0"
    >
    </div>
  </div>
  <ef-icon
    aria-hidden="true"
    icon="right"
    part="toggle"
    slot="left"
  >
  </ef-icon>
  <slot
    name="header-left"
    slot="left"
  >
  </slot>
  <slot
    name="header-right"
    slot="right"
  >
  </slot>
</ef-header>
<div
  aria-labelledby="header-toggle"
  id="content"
  part="content"
  role="region"
>
  <ef-panel
    part="content-data"
    transparent=""
  >
    <slot>
    </slot>
  </ef-panel>
</div>
`;
/* end snapshot collapse/Collapse Should Have Correct DOM Label and DOM structure is correct with level */

snapshots["collapse/Collapse Should Have Correct DOM Label and DOM structure is correct without level"] = 
`<ef-header
  level=""
  part="header"
>
  <div
    part="heading"
    role="heading"
  >
    <div
      aria-controls="content"
      aria-expanded="false"
      id="header-toggle"
      part="header-toggle"
      role="button"
      tabindex="0"
    >
    </div>
  </div>
  <ef-icon
    aria-hidden="true"
    icon="right"
    part="toggle"
    slot="left"
  >
  </ef-icon>
  <slot
    name="header-left"
    slot="left"
  >
  </slot>
  <slot
    name="header-right"
    slot="right"
  >
  </slot>
</ef-header>
<div
  aria-labelledby="header-toggle"
  id="content"
  part="content"
  role="region"
>
  <ef-panel
    part="content-data"
    transparent=""
  >
    <slot>
    </slot>
  </ef-panel>
</div>
`;
/* end snapshot collapse/Collapse Should Have Correct DOM Label and DOM structure is correct without level */

snapshots["collapse/Collapse Should Have Correct DOM Label and DOM structure is correct with header"] = 
`<ef-header
  level="3"
  part="header"
>
  <div
    part="heading"
    role="heading"
  >
    <div
      aria-controls="content"
      aria-expanded="false"
      id="header-toggle"
      part="header-toggle"
      role="button"
      tabindex="0"
    >
      Header
    </div>
  </div>
  <ef-icon
    aria-hidden="true"
    icon="right"
    part="toggle"
    slot="left"
  >
  </ef-icon>
  <slot
    name="header-left"
    slot="left"
  >
  </slot>
  <slot
    name="header-right"
    slot="right"
  >
  </slot>
</ef-header>
<div
  aria-labelledby="header-toggle"
  id="content"
  part="content"
  role="region"
>
  <ef-panel
    part="content-data"
    transparent=""
  >
    <slot>
    </slot>
  </ef-panel>
</div>
`;
/* end snapshot collapse/Collapse Should Have Correct DOM Label and DOM structure is correct with header */

snapshots["collapse/Collapse Should Have Correct DOM Label and DOM structure is correct"] = 
`<ef-header
  level="3"
  part="header"
>
  <div
    part="heading"
    role="heading"
  >
    <div
      aria-controls="content"
      aria-expanded="false"
      id="header-toggle"
      part="header-toggle"
      role="button"
      tabindex="0"
    >
    </div>
  </div>
  <ef-icon
    aria-hidden="true"
    icon="right"
    part="toggle"
    slot="left"
  >
  </ef-icon>
  <slot
    name="header-left"
    slot="left"
  >
  </slot>
  <slot
    name="header-right"
    slot="right"
  >
  </slot>
</ef-header>
<div
  aria-labelledby="header-toggle"
  id="content"
  part="content"
  role="region"
>
  <ef-panel
    part="content-data"
    transparent=""
  >
    <slot>
    </slot>
  </ef-panel>
</div>
`;
/* end snapshot collapse/Collapse Should Have Correct DOM Label and DOM structure is correct */

