name: 'Install and build'
description: 'Setup environment, install dependencies and build project'

runs:
  using: 'composite'
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ vars.NODE_VERSION }}
        registry-url: 'https://registry.npmjs.org'
        cache: 'npm'

    - name: Install Dependencies
      shell: bash
      run: npm ci --audit=false --fund=false

    - name: Build Packages
      shell: bash
      run: npm run build:prod
