name: Build Code
on:
  workflow_call:

jobs:
  build-code:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
        with:
          # Number of commits to fetch. 0 indicates all history for all branches and tags.
          # Pulls all commits (needed for Lerna)
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 15.x

      - name: Setup caching dependencies and build output scripts
        uses: ./.github/actions/cache
        id: cache

      - name: Install Dependencies
        if: steps.cache.outputs.dependencies-hit != 'true'
        run: |
          npm ci --ignore-scripts --audit=false --fund=false

      - name: Build changed packages
        if: steps.cache.outputs.build-hit != 'true'
        run: |
          lerna run build --include-dependencies --since origin/develop...HEAD
