name: Dev Release
on:
  pull_request:
    branches: [develop]
jobs:
  dev_release:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
        with:
          # Number of commits to fetch. 0 indicates all history for all branches and tags.
          # Pulls all commits (needed for Lerna)
          fetch-depth: 0
          token: ${{ secrets.GH_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          registry-url: 'https://registry.npmjs.org'
          cache: 'npm'

      - name: Configure Git User
        run: |
          git config --global user.email "RefinitivUIDev@refinitiv.com"
          git config --global user.name "refinitiv-ui-dev"

      - name: Dependencies Installation
        run: npm ci --ignore-scripts --audit=false --fund=false

      - name: Production build
        run: npm run build:prod

      - name: Publish to NPM
        run: lerna publish --canary --preid=build.${{ github.run_id }}.${{ github.run_attempt }} --no-changelog --no-git-tag-version --no-push --include-merged-tags --no-private --force-publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
