name: Dummy test lerna version

on:
  push:
    branches: [fix/ci-lerna-auto-update]

jobs:
  checkLerna:
    environment: development
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          # Number of commits to fetch. 0 indicates all history for all branches and tags.
          # Pulls all commits (needed for Lerna)
          fetch-depth: 0
          token: ${{ secrets.GH_TOKEN }}

      - name: Gather resources and build
        uses: ./.github/actions/checkout-install-and-build

      - name: Check lerna -v
        run: lerna -v

      - name: Check npx lerna -v
        run: npx lerna -v
