name: 'Pull Request Labeler'
on: pull_request_target

jobs:
  label:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/labeler@4f052778de9a9b80cb16cfb9079b02287285a4cb # v5.0.0-alpha.1
        with:
          repo-token: '${{ secrets.GITHUB_TOKEN }}'
