name: Lint
on:
  workflow_call:
  pull_request:
    branches: [test-develop]

jobs:
  lint-code:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
        with:
          # Number of commits to fetch. 0 indicates all history for all branches and tags.
          # Pulls all commits (needed for Lerna)
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 15.x

      - name: Setup caching dependencies and build output scripts
        uses: ./.github/actions/cache

      - run: lerna run lint --include-dependents --since origin/develop...HEAD
