name: Lint
on:
  pull_request:
    branches: [main]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
        # with:
        #   fetch-depth: 0

      - name: Fetch all history for all tags and branches to compare
        run: git fetch

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          # NPM 7 is compatible with Node.js 15 or above
          node-version: 15.x
          cache: 'npm'
      - run: npm ci --ignore-scripts --audit=false --fund=false
      - run: lerna run build --include-dependencies --since origin/main...HEAD
      - run: lerna run lint --include-dependents --since origin/main...HEAD
