name: 'PR Check'
on: [push] # Triggers on any branch
env:
  CI: 'true'
  NX_BASE: '6e60b5d7dce6c6b3ff0a1a4c627fb2bd968c64a9'
  BROWSERSTACK_USERNAME: ${{ secrets.BROWSERSTACK_USERNAME }}
  BROWSERSTACK_ACCESS_KEY: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}
  BROWSERSTACK_BUILD: 'Test ${{ github.run_number }}'
  BROWSERSTACK_LATEST_BROWSERS_LAUNCHER: 'Playwright'
  TEST_SSL_CERT: ${{ secrets.TEST_SSL_CERT }}
  TEST_SSL_KEY: ${{ secrets.TEST_SSL_KEY }}

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          # Number of commits to fetch. 0 indicates all history for all branches and tags.
          # Pulls all commits (needed for Lerna)
          fetch-depth: 0

      - name: Setup resources and environment
        uses: ./.github/actions/setup
        id: setup

      - name: Install Dependencies
        run: npm ci --audit=false --fund=false

      - name: Version
        run: |
          node -v
          npm -v

      - name: Build
        run: npm run build:affected

  test-chrome:
    name: 'Test / Chrome'
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Test
        uses: ./.github/actions/run-test
        with:
          browsers: 'chrome'

  scan-sonarcloud:
    name: Scan
    needs: test-chrome
    uses: ./.github/workflows/sonarcloud_scan.yml
    secrets: inherit
