name: SonarCloud Scan

on:
  workflow_call:
    inputs:
      log-level:
        description: 'Log level of scanning. Use DEBUG or TRACE for troubleshooting.'
        type: string
        default: INFO
  workflow_dispatch:
    inputs:
      log-level:
        description: 'Log level of scanning. Use DEBUG or TRACE for troubleshooting.'
        type: choice
        options:
          - INFO
          - DEBUG
          - TRACE
        default: INFO

jobs:
  sonarcloud:
    name: SonarCloud
    runs-on: ubuntu-latest
    # dependency scan is out of scope for SonarCloud
    if: github.actor != 'dependabot[bot]'
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup resources and environment
        uses: ./.github/actions/setup

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@49e6cd3b187936a73b8280d59ffd9da69df63ec9 # v2.1.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.log.level=${{inputs.log-level}}
