name: Nightly Test v7
on:
  schedule:
    - cron: '0 0 * * *'
env:
  USE_BROWSERSTACK: "true"
  BROWSERSTACK_USERNAME: ${{ secrets.BROWSERSTACK_USERNAME }}
  BROWSERSTACK_ACCESS_KEY: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}
  BROWSERSTACK_BUILD: "Nightly Test ${{ github.run_number }}"
  BROWSERSTACK_LATEST_BROWSERS_LAUNCHER: "Playwright"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          # Number of commits to fetch. 0 indicates all history for all branches and tags.
          # Pulls all commits (needed for Lerna)
          fetch-depth: 0
          ref: v7

      - name: Setup environment and resources with build
        uses: ./.github/actions/setup
        id: setup
        with:
          pre-build-script: npm run reset # temporary
          build-script: npm run build -- --skip-nx-cache # Prevent NX caching it should always build

  lint:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: v7

      - name: Setup environment and resources with build
        uses: ./.github/actions/setup

      - name: Lint
        # Prevent NX caching because it must run all linting, even though the code has not chaged.
        run: npm run lint:all -- --skip-nx-cache

  nightly-test:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: v7

      # Need this step for support feature toggle testing on BrowserStack on/off
      - name: Setup browser versions to testing
        run: |
          [[ "${{ env.USE_BROWSERSTACK }}" == "true" ]] && export BROWSERS="supported" || export BROWSERS="default"
          echo "BROWSERS=\"$BROWSERS\"" >> $GITHUB_ENV

      - name: Test
        uses: ./.github/actions/run-test
        with:
          browsers: ${{ env.BROWSERS }}
          mode: 'all'
          browserstack: $USE_BROWSERSTACK
          username: $BROWSERSTACK_USERNAME
          access-key: $BROWSERSTACK_ACCESS_KEY
