name: Test Run

on:
  push:
    branches: [fix/deprecated-solar]

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          # Number of commits to fetch. 0 indicates all history for all branches and tags.
          # Pulls all commits (needed for Lerna)
          fetch-depth: 0
          token: ${{ secrets.GH_TOKEN }}

      - name: Configure Git User
        run: |
          git config --global user.email "RefinitivUIDev@refinitiv.com"
          git config --global user.name "refinitiv-ui-dev"

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          registry-url: 'https://registry.npmjs.org'
          cache: 'npm'

      - name: Deprecate Solar Theme on npm
        run: |
          npm deprecate @refinitiv-ui/solar-theme "Solar theme is deprecated. Consider migrating to @refinitiv-ui/halo-theme instead."
        env:
          NPM_TOKEN: ${{ secrets.NPM_DEPRECATION_TOKEN }}
