name: Test Browser
on:
  workflow_call:
    inputs:
      browser:
        required: true
        type: string
        default: chrome
        description: input browser name for run test
      coverage:
        type: boolean
        default: false
        description: include code coverage testing
jobs:
  test-browser:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
        with:
          # Number of commits to fetch. 0 indicates all history for all branches and tags.
          # Pulls all commits (needed for Lerna)
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 15.x

      - name: Setup caching dependencies
        uses: actions/cache@v2
        with:
          path: |
            node_modules
            */*/node_modules
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}

      - name: Setup caching build
        uses: actions/cache@v2
        id: cache-build
        with:
          path: |
            packages/*/lib
            packages/*/light
            packages/*/dark
            packages/*/charcoal
            packages/*/pearl
          key: ${{ runner.os }}-build-${{ github.sha }}
          restore-keys: ${{ runner.os }}-build-${{ github.sha }}

      - run: lerna run test --include-dependents --since origin/develop...HEAD -- -- --browsers ${{inputs.browser}} --includeCoverage ${{inputs.coverage}}
